apiVersion: v1
kind: Namespace
metadata:
  name: other-projects
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: translator-bot-config
  namespace: other-projects
data:
  TARGET_LANGUAGE: "en"
  SOURCE_LANGUAGE: "ru"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: translator-bot
  namespace: other-projects
spec:
  replicas: 1
  selector:
    matchLabels:
      app: translator-bot
  template:
    metadata:
      labels:
        app: translator-bot
    spec:
      containers:
        - name: translator-bot
          image: towerton/translator:latest
          imagePullPolicy: Always
          volumeMounts:
            - name: iam-key
              mountPath: /app/iam-key
              readOnly: true
          envFrom:
          - secretRef:
              name: translatebot
          command: ["sh", "-c", "python3 translator-bot.py"]
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            runAsNonRoot: true
            runAsUser: 1000
      volumes:
        - name: iam-key
          secret:
            secretName: yandex-iam-key
      restartPolicy: Always

